apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
data:
  DB_NAME: analytics
  DB_USERNAME: analytics_user
  DB_HOST: postgres-service
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
type: Opaque
stringData:
  DB_PASSWORD: password
